--TABLA CUSTOMERS
CREATE TABLE [dbo].[TBL_CUSTOMERS]
(
	[ID] NVARCHAR(15) NOT NULL PRIMARY KEY, 
    [NAME] NVARCHAR(50) NOT NULL, 
    [LAST_NAME] NVARCHAR(50) NOT NULL, 
    [AGE] int NOT NULL
)

--INSERT EN  CUSTOMERS
CREATE PROCEDURE [dbo].[CRE_CUSTOMER_PR]
	@P_ID nvarchar(25),
	@P_NAME nvarchar(25),
	@P_LAST_NAME nvarchar(25),
	@P_AGE int
AS
	INSERT INTO [dbo].[TBL_CUSTOMERS] VALUES(@P_ID,@P_NAME,@P_LAST_NAME,@P_AGE);
GO;

--RETRIEVE ALL CUSTOMER
CREATE PROCEDURE [dbo].[RET_ALL_CUSTOMER_PR]
AS
	SELECT ID, NAME, LAST_NAME, AGE FROM TBL_CUSTOMERS;
RETURN 0


--UPDATE CUSTOMER
CREATE PROCEDURE [dbo].[UPD_CUSTOMER_PR]
	@P_ID nvarchar(25),
	@P_NAME nvarchar(25),
	@P_LAST_NAME nvarchar(25),
	@P_AGE int
AS
	UPDATE [dbo].[TBL_CUSTOMERS] SET NAME=@P_NAME, LAST_NAME=@P_LAST_NAME, AGE=@P_AGE WHERE ID=@P_ID;
GO;

--RET CUSTOMER BY ID
CREATE PROCEDURE [dbo].[RET_CUSTOMER_PR]
	@P_ID nvarchar(25)
AS
	SELECT ID, NAME, LAST_NAME, AGE FROM TBL_CUSTOMERS WHERE ID=@P_ID;
RETURN 0


--DELETE CUSTOMER
REATE PROCEDURE [dbo].[DEL_CUSTOMER_PR]
	@P_ID nvarchar(25)
AS
	DELETE FROM TBL_CUSTOMERS WHERE ID=@P_ID;
RETURN 0

